/*
 * static indication definitions for emotas_CANopen_Slave - generated by CANopen DeviceDesigner 3.4.1.2
 * Di Jun 16 13:32:40 2020
 */

/* protect against multiple inclusion of the file */
#ifndef GEN_INDICATION
#define GEN_INDICATION 1

/* 
   There are not any static indication functions defined.
   If there were some, they would be declared here. 
 */

#endif /* GEN_INDICATION*/
