/*
 *  index defines for emotas_CANopen_Slave - generated by CANopen DeviceDesigner 3.4.1.2
 * Di Jun 16 13:32:40 2020
 */

/* protect against multiple inclusion of the file */
#ifndef GEN_INDICES_H
#define GEN_INDICES_H 1

#define I_DEVICE_TYPE            	0x1000u
#define I_ERROR_REGISTER         	0x1001u
#define I_COB_ID_SYNC            	0x1005u
#define I_COB_ID_EMCY            	0x1014u
#define I_CONSUMER_HEARTBEAT_TIME	0x1016u
#define  S_CONSUMER_HEARTBEAT_TIME_1	0x1u
#define  S_CONSUMER_HEARTBEAT_TIME_2	0x2u
#define  S_CONSUMER_HEARTBEAT_TIME_3	0x3u
#define I_PRODUCER_HEARTBEAT_TIME	0x1017u
#define I_IDENTITY_OBJECT        	0x1018u
#define  S_VENDOR_ID              	0x1u
#define  S_PRODUCT_CODE           	0x2u
#define  S_REVISION_NUMBER        	0x3u
#define  S_SERIAL_NUMBER          	0x4u
#define I_SDO_SERVER_PARAMETER   	0x1200u
#define  S_COB_ID_CLIENT_TO_SERVER	0x1u
#define  S_COB_ID_SERVER_TO_CLIENT	0x2u
#define I_RECEIVE_PDO_COMMUNICATION_PARAMETER	0x1400u
#define  S_COB_ID                 	0x1u
#define  S_TRANSMISSION_TYPE      	0x2u
#define  S_INHIBIT_TIME           	0x3u
#define  S_EVENT_TIMER            	0x5u
#define I_RECEIVE_PDO_MAPPING_PARAMETER	0x1600u
#define  S_MAPPING_ENTRY_1        	0x1u
#define  S_MAPPING_ENTRY_2        	0x2u
#define I_TRANSMIT_PDO_COMMUNICATION_PARAMETER	0x1800u
#define I_TRANSMIT_PDO_MAPPING_PARAMETER	0x1a00u
#define I_UNSIGNED8_ARRAY        	0x2000u
#define  S_SUBINDEX_1             	0x1u
#define  S_SUBINDEX_2             	0x2u
#define  S_SUBINDEX_3             	0x3u
#define  S_SUBINDEX_4             	0x4u
#define I_UNSIGNED16_ARRAY       	0x2001u
#define  S_SUBINDEX_11            	0x1u
#define  S_SUBINDEX_21            	0x2u
#define  S_SUBINDEX_31            	0x3u
#define  S_SUBINDEX_41            	0x4u
#define I_INTEGER16_ARRAY        	0x2002u
#define  S_SUBINDEX_12            	0x1u
#define  S_SUBINDEX_22            	0x2u
#define  S_SUBINDEX_32            	0x3u
#define  S_SUBINDEX_4_WRITE_ONLY_ 	0x4u
#define I_MANUFACTURER_RECORD    	0x2003u
#define  S_U8                     	0x1u
#define  S_U16                    	0x2u
#define  S_U32                    	0x3u
#define  S_I8                     	0x4u
#define  S_I16                    	0x5u
#define  S_I32                    	0x6u
#define  S_R32                    	0x7u
#define  S_VS                     	0x8u
#define  S_NUMBER_OF_ENTRIES      	0x0u

#endif /* GEN_INDICES_H */
